### ISSUE TITLE
When getActualVersion fails, show stdout

### ISSUE THREAD

**Issue by LeeDr** [elastic/libesvm#34]
My java on windows is somehow messed up.  But it wasn't clear what the problem was. I added the stdout from a few lines above to the error output and now see that it's complaining about my Java installation.  There are a couple of different java problems that could be revealed by showing this output.

Line 19 of getActualVersion.js

```
    throw new Error('not sure how to get elasticsearch version. stdout=' + stdout);
```

```
$ esvm --branch master
Mar 15, 2016 9:41 AM INFO cluster Installing plugins
Mar 15, 2016 9:41 AM INFO cluster Starting 1 nodes
Oops Error:   Unable to get actual version:
  not sure how to get elasticsearch version. stdout=--help
  ,This version of C:\jdk1.8.0_60\bin\java.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

    at C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\lib\getActualVersion.js:45:11
    at tryCatcher (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Lee\AppData\Roaming\npm\node_modules\esvm\node_modules\libesvm\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by mjrk** [comment]
+1, I had a not enough memory error due to a broken Java install, and got the error "Cannot read property split of 'undefined'". This is because parseStdOut in `https://github.com/elastic/libesvm/blob/master/lib/getActualVersion.js` returns undefined for "not enough memory"
