### ISSUE TITLE
Library should check file system before depending on the network

### ISSUE THREAD

**Issue by meowsus** [elastic/libesvm#46]
This morning while running `esvm` (as I usually do in the mornings) nothing happened. I waited for a long while before getting the error:

```
Oops Error: Unable to find a version for "*"
    at /home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/libesvm/lib/resolveVersion.js:39:11
    at tryCatcher (/home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/meowsus/.nvm/versions/node/v7.4.0/lib/node_modules/esvm/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Ah yes. The dreaded Oops Error!

I figured that [the endpoint](https://esvm-props.kibana.rocks/builds) that supplies the library with it's list of builds was down, and sure enough it was... and still is, actually.

So I peeked at my `~/.esvm` directory:

```
~ $ ls ~/.esvm
1.5.2  2.4.0  5.2.1  5.2.2  5.3.0  branch-5.x
```

And figured I could just run `esvm 5.3.0` to tell the library to stop caring about the internet and just run the version I want locally. Still no dice.

Can we get a fix pushed so that `libesvm` stops trying to hit the build endpoint if we explicitly tell it to grab a locally installed version?

cc: @spalger because he's the best.

**Comment by spalger** [comment]
👍  esvm isn't planning to download the file there is no reason to pull the manifest from esvm-props

**Comment by meowsus** [comment]
@spalger I hit this error again and, after confirming that my connection wasn't down, I realized that your kibana.rocks server is down: https://esvm-props.kibana.rocks/builds

Would you mind kickstarting this guy for us? I can spend some time today trying to get a PR together for esvm to resolve this issue a bit more permanently.

**Comment by meowsus** [comment]
Looks like the server is back up. Thank you. I ran out of time looking into the feature we discussed here, but I'll try to do that soon.

**Comment by meowsus** [comment]
@spalger Looks like https://esvm-props.kibana.rocks/builds lost it's SSL Cert, rendering `esvm` useless again.

**Comment by tunnes** [comment]
@meowsus I'm having the same problem, can you tell me if this is seasonal? As an alternative I'm using evm [evm](https://github.com/duydo/evm), but in production my application still depends on the svm =(

**Comment by JakeBeresford** [comment]
@spalger same issue here.

**Comment by kristenward** [comment]
Having this issue now also.

**Comment by meowsus** [comment]
Thanks, looks like the build server is back.

**Comment by thomasv314** [comment]
bump 👍

**Comment by spalger** [comment]
Sorry everyone, SSL cert is fixed. Was behind on Github for a couple days 😅
