### ISSUE TITLE
Domain certificate for `fetchAllTags` has expired

### ISSUE THREAD

**Issue by ghmeier** [elastic/libesvm#56]
In [`fetchAllTags`](https://github.com/elastic/libesvm/blob/master/lib/fetchAllTags.js#L11) you request https://esvm-props.kibana.rocks/builds to get a list of valid builds. However, the certificate for this domain expired sometime in the last 24 hours so the request fails with:
```
{ Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
  cause: { Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'CERT_HAS_EXPIRED' },
  isOperational: true,
  code: 'CERT_HAS_EXPIRED' }
```

Can someone message the owners to update their certificate?

**Comment by skeggse** [comment]
See also https://github.com/elastic/libesvm/issues/46#issuecomment-404211413

**Comment by ghmeier** [comment]
🙌 Looks like it's working again, thanks!
